### ISSUE TITLE
Problem with login in AD

### ISSUE THREAD

**Issue by pwldp** [typ90/meteor-accounts-ldap#1]
Hi,
I use npm active directory module (https://github.com/gheeres/node-activedirectory) and I can authenticate to AD.
When I use meteor-accounts-ldap I got an error: ```"80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 57, v1db1```.
I use the same url, dn, username and password in both situations.

Whats wrong?

**Comment by typ90** [comment]
@pwldp can you provide sample code (without credentials) for me to look at?

**Comment by typ90** [comment]
Also, this hasn't yet been tested against Microsoft AD. I'll try to set up some code examples for it.

**Comment by pwldp** [comment]
Hi,
I use js file created after ```meteor create PROJEKCTNAM``` file and my code is:
```
if (Meteor.isClient) {
  // counter starts at 0
  Session.setDefault('counter', 0);
  

  Template.hello.helpers({
    counter: function () {
      return Session.get('counter');
    }
  });

  Template.hello.events({
    'click button': function () {
      // increment the counter when button is clicked
      Session.set('counter', Session.get('counter') + 1);
        //--LDAP
        var username = "UUUUUU";
        var password = "PPPPPPP";
        
        Meteor.loginWithLDAP(username, password, {
        }, function(err) {
        if (err)console.log(err.reason);
        else console.log("Login passed!"); 
            
        });        
        //--LDAP
        
    }
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
        LDAP_DEFAULTS.url= "ldap://__IP__";
        LDAP_DEFAULTS.dn= "ou=XXX,dc=XXX,dc=XX";
        LDAP_DEFAULTS.defaultDomain = "XXX.XX";
        LDAP_DEFAULTS.createNewUser = true;
  });
}
```

**Comment by fehmer** [comment]
Hi @typ90, @pwldp,

i had some troubles integrating accounts-ldap with an AD as well.

I found out that i was only able to bind the user using ```<domain>/<username>```. But for the LDAP search used to gather more information about the user with the ```searchResultsProfileMap```i need to use a ldap query with a filter.

I forked the project and [modified](https://github.com/fehmer/meteor-accounts-ldap/commit/650a998fa5695c384c797d16081c523f757e52e3) it for my needs.

@pwldp  if you want to try my patch please give me a feedback

**Comment by typ90** [comment]
@fehmer I was planning on rewriting a lot of the package to accommodate to how different people have been using it. Would you want to submit a PR and I can close out this issue?

**Comment by fehmer** [comment]
Hi @typ90,

i've submitted a PR, please have a look, thank you.

**Comment by fehmer** [comment]
Hi @typ90, thanks for accepting the PR. Can you please increase the version number and release it to atmosphere?

**Comment by dpdonohue** [comment]
I second @fehmer 's request!  Thank you both for your work

**Comment by typ90** [comment]
New version has been published to atmosphere. Thanks for the work on this @fehmer - sorry for leaving the package unmaintained for so long.

**Comment by DarkStar1** [comment]
@pwldp I have the same LDAP error code from an entirely different scenario. Any idea what the hex code 57 means? I can't seem to find any documentation related to that code anywhere.

**Comment by pwldp** [comment]
@DarkStar1 maybe this will help you: https://community.boomi.com/docs/DOC-3022

**Comment by DarkStar1** [comment]
@pwldp No that doesn't help as that's for error code 53. I would like to find an explanation for *data code 57* for error code 49.
