### ISSUE TITLE
Logging in with no password succeeds

### ISSUE THREAD

**Issue by fletchgqc** [typ90/meteor-accounts-ldap#10]
I'm using this code:
```javascript
Meteor.loginWithLDAP(username, password,
	{ dn: username + '@banana.org' },
	function(err) {
		if (err) {
			console.log(err);
			FlashMessages.sendError("Login failed");
			event.target.password.value = "";
		} else {
			console.log("Login succeeded");
		}
	}
);
```

Authentication with user/password succeeds and fails as expected, except that when I leave the password empty, login succeeds. Why is this?

**Comment by darrenangle** [comment]
+1

**Comment by doomdance** [comment]
I'm also experiencing this but it looks like it may be specific to the AD set up as mentioned in this nodejs issue: https://github.com/mcavage/node-ldapjs/issues/191

**Comment by fletchgqc** [comment]
Thanks doomdance. I think you are right. I think logging at least an info message with a link to the RFC would be the best behaviour of the module. Anyway, I'll check for empty password manually.
