### ISSUE TITLE
Needs accounts-password

### ISSUE THREAD

**Issue by rmbrich** [typ90/meteor-accounts-ldap#13]
Hi @typ90, great job on this so far. Got it working with my company's Active Directory environment.

Just an FYI - if createNewUser is enabled, but the meteor **accounts-password** package is not installed, this error is thrown on the server upon successful LDAP login:
`Exception while invoking method 'login' TypeError: Object [object Object] has no method 'createUser'`

Doing a `meteor add accounts-password` fixes the problem. Maybe you should make your package depend on **accounts-password** or at least call this out in the documentation.

Thanks!
Rob

**Comment by typ90** [comment]
Hi Rob!

I've added `accounts-password` dependency to the project.
