### ISSUE TITLE
Potential problem

### ISSUE THREAD

**Issue by sebakerckhof** [typ90/meteor-accounts-ldap#2]
Hello,

Let me start of by saying I haven't tested the code, since I don't have an LDAP server nearby. But I just went through the code and wondered if this isn't going to give a problem:

```js
return {
			userId: userId,
			token: stampedToken.token
		};
````
In the case where the user doesn't exist, since then no stampedToken is going to be present, as it is only generated when a user already exists but it is returned in both cases...

**Comment by typ90** [comment]
@sebakerckhof It is initially set to `null` so if a user does not exist and isn't being created, it will remain `null`. But in general you're right, it's just sloppy code. I plan on cleaning up the server code in the coming days.
